version: '3.1'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
        - envs.env
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
        - envs.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    ports:
      - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
